# Generated by Django 6.0.2 on 2026-02-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pix',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to='profile'),
        ),
    ]
